  - name: Ensure MySQL packages are installed.
    apt:
      name: "{{ mysql_packages }}"
      state: present
    register: mysql_install_packages

  - name: Make sure pymysql is present
    become: true # needed if the other tasks are not played as root
    pip:
      name: pymysql
      state: present

  - name: Start the MySQL service
    action: service name=mysql state=started

  - name: restart mysql
    service: "name={{ mysql_daemon }} state=restarted"
  
  - name: Ensure default user is present.
    mysql_user:
      host: "{{ item }}"
      name: "{{ mysql_root_username }}"
      password: "{{ mysql_root_password }}"
      check_implicit_admin: "yes"
      login_user: 'root'
      login_password: 'root'
      priv: '*.*:ALL,GRANT'
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock
    with_items:
    - 127.0.0.1
    - 192.168.33.20
    - ::1
    - localhost

  - name: copy .my.cnf file with root password credentials
    template: src=templates/root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

  - name: delete anonymous MySQL server user for $server_hostname
    action: mysql_user login_unix_socket="/var/run/mysqld/mysqld.sock" user="" host="{{ server_hostname }}" state="absent"

  - name: delete anonymous MySQL server user for localhost
    action: mysql_user login_unix_socket="/var/run/mysqld/mysqld.sock" user="" state="absent"

  - name: remove the MySQL test database
    action: mysql_db login_unix_socket="/var/run/mysqld/mysqld.sock" db=test state=absent

  - name: install maven (and other packages if needed)
    become: yes
    apt: pkg=maven state=latest update_cache=yes cache_valid_time=3600
