- hosts: local
  gather_facts: false
  become: yes
  # vars_files:
  #  - ./vars/vars.yml
  tasks: 
  # - name: "Copy ansible-srv:/bakerx/fuzzer to config-srv:/home/vagrant/fuzzer"
  #   copy:
  #     src: /bakerx/fuzzer
  #     dest: ""
  - name: Set git environment variables {{gitHubUser}}
    lineinfile:
      path: /etc/environment
      line: "GH_USER={{ gitHubUser }}\n GH_PASS={{ gitHubPassword }}"

  - name: Copy iTrustBuild.Unix.sh to config-srv:/home/vagrant
    copy:
      src: /bakerx/pipeline/roles/iTrust_env/templates/iTrustBuild.Unix.sh
      dest: "/home/vagrant/iTrustBuild.sh"

  - name: install dos2unix
    apt:
      name: dos2unix
  
  - name: Dos2Unix iTrustBuild.sh
    shell: "dos2unix /home/vagrant/iTrustBuild.sh"

  - name: run command 
    shell: "bash /home/vagrant/iTrustBuild.sh"
    become: yes

  - name: install node packages in /bakerx/fuzzer
    npm:
      path: "/bakerx/fuzzer"
      
  - name: Run iTrust test {{check}} time(s)
    shell: node /bakerx/fuzzer/FS.js {{check}}
    become: yes

  - name: fetch
    fetch:
      src: "/bakerx/result.txt"
      dest: /bakerx/results

  - name: Print results
    debug: var=item
    with_file:
      - "/bakerx/results/192.168.33.20/home/vagrant/result.txt"