- hosts: local
  become: yes
  tasks:
    - name: Stage build
      include: ./roles/iTrust-prod/tasks/stage.yml
- hosts: itrust
  become: yes
  roles:
    - app-common
    - java
    - tomcat
    - iTrust
    - iTrust-prod