- name: Create staging directory
  shell: mkdir -p /tmp/builds/checkbox.io

- name: Download latest build
  shell: curl http://192.168.33.20:9000/job/checkbox.io/lastSuccessfulBuild/artifact/*zip*/archive.zip --output /tmp/builds/checkbox.io/checkbox.io.zip
