- name: Add nodejs repository
  shell: 'curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -'
  become: yes

- name: Install nodejs & npm
  apt:
    pkg:
    - nodejs
    state: latest
  become: yes

- include: ../../nginx/tasks/install.yml