---
- include_vars: main.yml

- name: Update apt pm repo cache 
  apt: 
    update_cache: true

- name: Install java & jenkins job builder
  apt:
    pkg:
    - openjdk-11-jdk
    - jenkins-job-builder
    state: present

- name: Add Jenkins apt repository key.
  apt_key:
    url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
    state: present

    
- name: Add Jenkins apt repository.
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present
    update_cache: true


- name: ensure jenkins is installed
  apt: name=jenkins update_cache=yes

  # Configure Jenkins.
- include_tasks: configure.yml

- name: Create initialization scripts directory
  file: path={{ jenkins_home }}/init.groovy.d
        state=directory
        owner=jenkins
        group=jenkins
        mode=0775

- name: Add initialization script to setup basic security
  template: src=/bakerx/pipeline/basic-security.groovy
            dest={{ jenkins_home }}/init.groovy.d/basic-security.groovy

- name: ensure jenkins is running
  service: name=jenkins state=started enabled=yes

- name: Restart jenkins service so configurations are applied
  ansible.builtin.service:
    name: jenkins
    state: restarted

- name: Wait for jenkins to come up
  uri:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli/"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 100
  delay: 5
  changed_when: false
  check_mode: false

# Update Jenkins and install configured plugins.
- include_tasks: plugins.yml
