#
# Example of a Play which handles Jenkins restarts during the state changes
#
    - name: Install plugins without a specific version
      jenkins_plugin:
        name: "{{ item.key }}"
        url: "http://localhost:9000/"
        url_username: "{{ jenkins_admin_username }}"
        url_password: "{{ jenkins_admin_password }}"
        force_basic_auth: yes
      register: jenkins_plugin_unversioned
      when: >
        'version' not in item.value
      with_dict: "{{ jenkins_plugins }}"
      retries: 5
      delay: 3

    - name: Install plugins with a specific version
      jenkins_plugin:
        name: "{{ item.key }}"
        url: "http://localhost:9000/"
        version: "{{ item.value['version'] }}"
        url_username: "{{ jenkins_admin_username }}"
        url_password: "{{ jenkins_admin_password }}"
        force_basic_auth: yes
      register: jenkins_plugin_versioned
      when: >
        'version' in item.value
      with_dict: "{{ jenkins_plugins }}"
      retries: 2
      delay: 3

    - name: Initiate the fact
      set_fact:
        jenkins_restart_required: no

# Pause for a minute for jenkins-plugins to install.
    - name: Pausing for a minute for jenkins-plugin install to complete
      pause:
        minutes: 1

    - name: Check if restart is required by any of the versioned plugins
      set_fact:
        jenkins_restart_required: yes
      when: item.changed
      with_items: "{{ jenkins_plugin_versioned.results }}"

    - name: Check if restart is required by any of the unversioned plugins
      set_fact:
        jenkins_restart_required: yes
      when: item.changed
      with_items: "{{ jenkins_plugin_unversioned.results }}"

    - name: Restart Jenkins if required
      service:
        name: jenkins
        state: restarted
      when: jenkins_restart_required

    - name: Wait for Jenkins to start up
      uri:
        url: http://localhost:9000
        status_code: 200
        timeout: 5
      register: jenkins_service_status
      # Keep trying for 5 mins in 5 sec intervals
      retries: 60
      delay: 5
      until: >
         'status' in jenkins_service_status and
         jenkins_service_status['status'] == 200
      when: jenkins_restart_required

    - name: Reset the fact
      set_fact:
        jenkins_restart_required: no
      when: jenkins_restart_required

