- name: Get Jenkins crumb
  uri:
    user: admin
    password: admin
    force_basic_auth: yes
    url: "http://192.168.33.20:9000/crumbIssuer/api/json"
    return_content: yes
  register: crumb_token
  until: crumb_token.content.find('Please wait while Jenkins is getting ready') == -1
  retries: 10
  delay: 5

- name: Set crumb token
  set_fact:
    crumb: "{{ crumb_token.json.crumbRequestField }}={{ crumb_token.json.crumb }}"

- name: Install plugins
  uri:
    user: admin
    password: admin
    force_basic_auth: yes
    url: "http://192.168.33.20:9000/pluginManager/install?plugin.{{ item }}.default=on&{{ crumb }}"
    method: POST
    status_code: [200, 302]
  with_items: "{{ jenkins_plugins }}"


- name: Wait for plugins to be installed
  uri:
    url: "http://192.168.33.20:9000/updateCenter/installStatus?{{ crumb }}"
    return_content: yes
  register: plugin_status
  until: "'Pending' not in plugin_status.json.data.jobs|map(attribute='installStatus')"
  retries: 60
  delay: 10

- name: Check if we need to restart Jenkins to activate plugins
  uri:
    url: "http://192.168.33.20:9000/updateCenter/api/json?tree=restartRequiredForCompletion&{{ crumb }}"
    return_content: yes
  register: jenkins_restart_required

- name: Restart Jenkins to activate new plugins
  service: name=jenkins state=restarted
  when: jenkins_restart_required.json.restartRequiredForCompletion|bool

- name: Wait for Jenkins to become available
  wait_for: port=9000