---

# - name: Install Forever
#   command: npm install forever -g

- name: Checks if checkbox.io already exists
  command: bash -c "cd /tmp; if [ -d "checkbox.io" ]; then rm -Rf "checkbox.io"; fi"

- name: Clone Checkbox.io
  git:
    repo: 'https://github.com/chrisparnin/checkbox.io.git'
    dest: /tmp/checkbox.io

- name: Install NPM Dependencies for Checkbox.io
  npm:
    path: /tmp/checkbox.io/server-side/site
    state: latest

- name: Replace Default Nginx Configuration
  copy:
    src: default
    dest: /etc/nginx/sites-available/default

- name: Start Nginx Service
  systemd:
    state: reloaded
    name: nginx

# Install and start redis server

- name: Install redis-server
  command: apt-get install redis-server -y

- name: Start redis server
  command: bash -c "systemctl stop redis-server; systemctl start redis-server"

- name: Set checkbox ip addresses as environment variables
  lineinfile:
    path: /etc/environment
    regexp: '^CHECKBOX_IP=.+'
    line: "CHECKBOX_IP={{hostvars[inventory_hostname]['groups']['checkbox'][0]}}"
    create: yes

- name: Start checkbox
  command: forever start --sourceDir /tmp/checkbox.io/server-side/site/ server.js server
  environment:
    APP_PORT: "{{app_port}}"
    MONGO_PORT: "{{mongo_port}}"
    MONGO_USER: "{{mongo_user}}"
    MONGO_PASSWORD: "{{mongo_password}}"
    MONGO_IP: "{{mongo_ip}}"